name = "Optuna"
uuid = "a5d0552b-b2dc-4f08-ac5c-85ca7d701b92"
authors = ["JT <julian.trommer@uni-a.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
